/gate/geometry/setMaterialDatabase ../data/GateMaterials.db 

/gate/world/geometry/setXLength 2. m 
/gate/world/geometry/setYLength 2. m 
/gate/world/geometry/setZLength 2. m 
/gate/world/setMaterial Air 
/gate/world/vis/setVisible 0 

/gate/world/daughters/name CTscanner 
/gate/world/daughters/insert box 
/gate/CTscanner/setMaterial Tungsten 
/gate/CTscanner/geometry/setXLength 25 mm 
/gate/CTscanner/geometry/setYLength 25 mm 
/gate/CTscanner/geometry/setZLength 5 mm 
/gate/CTscanner/vis/forceSolid 
/gate/CTscanner/vis/setColor yellow 
/gate/CTscanner/placement/setTranslation 0. 0. 5. cm 

/gate/world/daughters/name Phantom
/gate/world/daughters/insert cylinder
/gate/Phantom/placement/setTranslation 0.0 0.0 0.0 cm 
/gate/Phantom/setMaterial PMMA
/gate/Phantom/geometry/setRmax 6 mm
/gate/Phantom/geometry/setRmin 0 mm
/gate/Phantom/geometry/setHeight 10 mm
/gate/Phantom/vis/forceWireframe
/gate/Phantom/vis/setColor red
/gate/Phantom/vis/setVisible 1 

/gate/Phantom/placement/setRotationAxis 0 1 0 
/gate/Phantom/placement/setRotationAngle 2.258065 deg 
 
/gate/Phantom/daughters/name Micro1
/gate/Phantom/daughters/insert sphere
/gate/Micro1/setMaterial HA
/gate/Micro1/geometry/setRmax 0.3 mm
/gate/Micro1/geometry/setRmin 0 mm
/gate/Micro1/vis/forceSolid
/gate/Micro1/vis/setColor blue
/gate/Micro1/vis/setVisible 1
/gate/Micro1/repeaters/insert linear
/gate/Micro1/linear/setRepeatNumber  5
/gate/Micro1/linear/setRepeatVector  0.  1.5 0. mm
/gate/Micro1/placement/setTranslation 3.5 0.0 -1. mm

/gate/Phantom/daughters/name Micro2
/gate/Phantom/daughters/insert sphere
/gate/Micro2/setMaterial HA
/gate/Micro2/geometry/setRmax 0.6 mm
/gate/Micro2/geometry/setRmin 0 mm
/gate/Micro2/vis/forceSolid
/gate/Micro2/vis/setColor blue
/gate/Micro2/vis/setVisible 1
/gate/Micro2/repeaters/insert linear
/gate/Micro2/linear/setRepeatNumber  5
/gate/Micro2/linear/setRepeatVector  0.  1.5 0. mm
/gate/Micro2/placement/setTranslation 2.5 0.0 -3. mm

/gate/Phantom/daughters/name Al203
/gate/Phantom/daughters/insert sphere
/gate/Al203/setMaterial OX
/gate/Al203/geometry/setRmax 0.3 mm
/gate/Al203/geometry/setRmin 0 mm
/gate/Al203/vis/forceSolid
/gate/Al203/vis/setColor yellow
/gate/Al203/vis/setVisible 1
/gate/Al203/repeaters/insert linear
/gate/Al203/linear/setRepeatNumber  5
/gate/Al203/linear/setRepeatVector  0.  1.5 0. mm
/gate/Al203/placement/setTranslation -3.5 0.5 0. mm

/gate/Phantom/daughters/name Al204
/gate/Phantom/daughters/insert sphere
/gate/Al204/setMaterial OX
/gate/Al204/geometry/setRmax 0.6 mm
/gate/Al204/geometry/setRmin 0 mm
/gate/Al204/vis/forceSolid
/gate/Al204/vis/setColor yellow
/gate/Al204/vis/setVisible 1
/gate/Al204/repeaters/insert linear
/gate/Al204/linear/setRepeatNumber  5
/gate/Al204/linear/setRepeatVector  0.  1.5 0. mm
/gate/Al204/placement/setTranslation -2.5 0.5 -3. mm 
 
/gate/physics/addPhysicsList emstandard_opt4 


/gate/actor/addActor DoseActor     MyActor 

/gate/actor/MyActor/save                        MyOutputFile19.mhd 

/gate/actor/MyActor/attachTo                    CTscanner 
/gate/actor/MyActor/setResolution               256 256 1 
/gate/actor/MyActor/stepHitType                 post 


/control/verbose 0 
/run/verbose 0 
/run/particle/verbose 0 
/event/verbose 0 
/tracking/verbose 0 
/tracking/verbose 0 
/gate/generator/verbose 0 
/gate/source/verbose 0 
/run/particle/verbose 0 

/gate/run/initialize
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/source/addSource electron_beam gps
/gate/source/electron_beam/gps/particle gamma 
/gate/source/electron_beam/gps/ene/type Gauss 
/gate/source/electron_beam/gps/ene/mono 0.02 MeV 
/gate/source/electron_beam/gps/ene/sigma 0.00216 MeV 
/gate/source/electron_beam/gps/centre 0 0 -23 cm 
/gate/source/electron_beam/gps/angtype iso 
/gate/source/electron_beam/gps/mintheta 0 deg 
/gate/source/electron_beam/gps/maxtheta 0 deg 
/gate/source/electron_beam/gps/minphi 0 deg 
/gate/source/electron_beam/gps/maxphi 0 deg 
/gate/source/electron_beam/gps/type Plane 
/gate/source/electron_beam/gps/shape Square
/gate/source/electron_beam/gps/halfx 15 mm
/gate/source/electron_beam/gps/halfy 15 mm

/gate/application/setTotalNumberOfPrimaries 1e8 
/gate/application/start 

